# Generated by Django 5.2.5 on 2025-09-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=500)),
                ('category_slug', models.CharField(default='', max_length=500)),
                ('category_description', models.CharField(default='', max_length=1200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(default='', max_length=500)),
                ('tag_slug', models.CharField(default='', max_length=500)),
                ('tag_description', models.CharField(default='', max_length=1200)),
            ],
        ),
        migrations.CreateModel(
            name='SongList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=300)),
                ('thumb_images', models.ImageField(blank=True, default='', upload_to='media/store/images/thumbimages')),
                ('body', models.TextField()),
                ('chords', models.TextField(blank=True, default=None, null=True)),
                ('ppt', models.FileField(blank=True, default='', upload_to='media/store/pdfs')),
                ('description', models.TextField()),
                ('article_title', models.CharField(default='', max_length=400)),
                ('slug', models.CharField(blank=True, max_length=1000, null=True)),
                ('lyricsslug', models.CharField(blank=True, max_length=1000, null=True)),
                ('song_views', models.IntegerField(default=0)),
                ('song_todayviews', models.IntegerField(default=0)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('englishlyrics', models.TextField()),
                ('tanglishlyrics', models.TextField()),
                ('english_trans_lyrics', models.TextField(blank=True, null=True)),
                ('last_viewed', models.DateTimeField(auto_now_add=True)),
                ('ppt_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('tamil_lyrics', models.TextField(blank=True, null=True)),
                ('thanglish_lyrics', models.TextField(blank=True, null=True)),
                ('presenter_views', models.IntegerField(default=0)),
                ('presenter_todayviews', models.IntegerField(default=0)),
                ('Categorys', models.ManyToManyField(to='myapp.category')),
                ('Tag', models.ManyToManyField(to='myapp.tag')),
            ],
        ),
    ]
