# Generated by Django 5.2.5 on 2025-09-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favouritelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(default='', max_length=400)),
                ('username', models.CharField(default='', max_length=400)),
                ('userid', models.CharField(default='', max_length=400)),
            ],
        ),
    ]
