# Generated by Django 5.2.5 on 2025-10-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_favouritelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favouritesongsnew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=400)),
                ('fav_id', models.CharField(default='', max_length=200)),
                ('song', models.CharField(default='', max_length=400)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('playlistname', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
